version: "3"
services:
  app:
    container_name: multiContianerDemoFlaskStorage
    build: ./app
    restart: always
    links: 
      - db
    ports: 
    - "5000:5000"
  db:
    image: mysql:8.0.21
    container_name: mysqlDemoStorage
    restart: always
    command: '--default-authentication-plugin=mysql_native_password'
    ports:
       - "30000:3306"
    environment:
      MYSQL_USER: "root"
      MYSQL_ROOT_PASSWORD: "admin"
      
    volumes:
      - ./db/:/docker-entrypoint-initdb.d/:ro